sudo: required
language: python            # this works for Linux but is an error on macOS or Windows
addons:
  apt:
    packages:
      - xvfb
matrix:
  fast_finish: true
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
  allow_failures:
    - os: windows           # Windows 10.0.17134 N/A Build 17134
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm
install:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
  - sleep 3
  - pip3 install --upgrade pip || pip3 install --upgrade --user pip  # --user is required for Windows
  - pip3 install -r requirements.txt || pip3 install -r --user requirements.txt
  - pip3 install pytest pytest-cov codecov || pip3 install --user pytest pytest-cov codecov  # install coverage monitor
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
before_script:
  - "herbstluftwm &"
  - sleep 1
script:
  - pytest --cov=./

cache: pip

after_success:
  - codecov
